# test-fireworks-kimi.ps1
# Smoke test for the Fireworks AI Kimi K2 judge tier.
#
# Reads $env:FIREWORKS_API_KEY, sends a minimal text-only Chat Completions
# request, verifies a non-empty response, and writes a redacted receipt to
# docs/proof/fireworks-kimi-smoke-receipt.md.
#
# Usage:
#   $env:FIREWORKS_API_KEY = '<your key>'  # already set in this environment
#   pwsh -File scripts/proof/test-fireworks-kimi.ps1
#
# Exit codes:
#   0  PASS — non-empty response received
#   1  FAIL — missing key, HTTP error, or empty response

[CmdletBinding()]
param(
    [string]$Model = 'accounts/fireworks/models/kimi-k2-instruct',
    [string]$Prompt = 'Describe what you see in 1 sentence.',
    [int]$TimeoutSec = 30
)

$ErrorActionPreference = 'Stop'

if (-not $env:FIREWORKS_API_KEY) {
    # Fallback to User-scope env var (Windows: persisted but not always inherited by subprocesses)
    $userKey = [Environment]::GetEnvironmentVariable('FIREWORKS_API_KEY', 'User')
    if ($userKey) {
        $env:FIREWORKS_API_KEY = $userKey
    } else {
        Write-Error '[FAIL] FIREWORKS_API_KEY env var is not set (checked Process and User scopes).'
        exit 1
    }
}

$endpoint = 'https://api.fireworks.ai/inference/v1/chat/completions'

$body = @{
    model       = $Model
    messages    = @(
        @{ role = 'user'; content = $Prompt }
    )
    temperature = 0.0
    max_tokens  = 128
} | ConvertTo-Json -Depth 6 -Compress

$headers = @{
    'Authorization' = "Bearer $env:FIREWORKS_API_KEY"
    'Content-Type'  = 'application/json'
    'Accept'        = 'application/json'
}

Write-Host "[INFO] POST $endpoint  model=$Model"

$startedUtc = [DateTime]::UtcNow.ToString('o')
$status = 'unknown'
$httpStatus = $null
$content = $null
$errorMessage = $null

try {
    $response = Invoke-WebRequest -Uri $endpoint -Method Post `
        -Headers $headers -Body $body `
        -TimeoutSec $TimeoutSec -UseBasicParsing
    $httpStatus = [int]$response.StatusCode
    $data = $response.Content | ConvertFrom-Json
    $content = $data.choices[0].message.content
    if ([string]::IsNullOrWhiteSpace($content)) {
        $status = 'fail-empty-response'
    } else {
        $status = 'pass'
    }
} catch {
    $status = 'fail-exception'
    $errorMessage = $_.Exception.Message
    if ($_.Exception.Response) {
        try { $httpStatus = [int]$_.Exception.Response.StatusCode } catch { $httpStatus = $null }
    }
    if ($_.ErrorDetails -and $_.ErrorDetails.Message) {
        $errorMessage = "$errorMessage`n$($_.ErrorDetails.Message)"
    }
}

# Print summary (no key)
Write-Host "[RESULT] status=$status http=$httpStatus"
if ($content) {
    $excerpt = $content
    if ($excerpt.Length -gt 240) { $excerpt = $excerpt.Substring(0, 240) + '...' }
    Write-Host "[EXCERPT] $excerpt"
}
if ($errorMessage) {
    Write-Host "[ERROR] $errorMessage"
}

# Write redacted receipt
$repoRoot = (Resolve-Path "$PSScriptRoot\..\..").Path
$receiptPath = Join-Path $repoRoot 'docs\proof\fireworks-kimi-smoke-receipt.md'
$receiptDir = Split-Path $receiptPath -Parent
if (-not (Test-Path $receiptDir)) { New-Item -ItemType Directory -Path $receiptDir | Out-Null }

$excerptForFile = if ($content) {
    $clean = $content -replace '\r', ''
    if ($clean.Length -gt 400) { $clean.Substring(0, 400) + '...' } else { $clean }
} else { '(no content returned)' }

$md = @"
# Fireworks AI Kimi K2 — Smoke Test Receipt

- **Provider**: Fireworks AI
- **Endpoint**: ``$endpoint``
- **Model**: ``$Model``
- **Prompt**: ``$Prompt``
- **Status**: **$status**
- **HTTP status**: $httpStatus
- **Started (UTC)**: $startedUtc
- **API key**: redacted — sourced from `` `$env:FIREWORKS_API_KEY `` (never written to disk; backtick escapes `$` in PowerShell here-string)

## Response excerpt

> $excerptForFile

$( if ($errorMessage) { "## Error`n`n``````$errorMessage```````n" } else { '' } )

---
Generated by ``scripts/proof/test-fireworks-kimi.ps1``.
"@

Set-Content -Path $receiptPath -Value $md -Encoding UTF8
Write-Host "[INFO] Receipt written to $receiptPath"

if ($status -eq 'pass') { exit 0 } else { exit 1 }
