name: Trufflehog Secrets Scan
on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@a795abf9397540a3e7c4846105b5a89f39d0d053 # v3.82.x
        with:
          extra_args: --results=verified
